In [365]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [366]:
PO_FILE_PATH = 'Book1_TECHNO.csv'
CO_FILE_PATH = 'Book2_TECHNO.csv'
HUMAN_MAPPING = 'CO_POMapping_TECHNO_BINARY.csv'

In [367]:
po_df = pd.read_csv(PO_FILE_PATH)
co_df = pd.read_csv(CO_FILE_PATH)

Program Outcomes

In [368]:
po_data = po_df.copy()
count_vectorizer = CountVectorizer(stop_words='english', min_df=0.005)

In [369]:
po_data['PO_Description'] = po_data['PO_Description'].str.lower()
po_corpus = po_data['PO_Description'].tolist()
po_corpii = count_vectorizer.fit_transform(po_corpus)
po_corpii

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 276 stored elements and shape (13, 182)>

In [370]:
po_feature_names = count_vectorizer.get_feature_names_out()
po_feature_names

array(['able', 'accordance', 'address', 'adverse', 'aligned',
       'analytical', 'analyze', 'application', 'applied', 'apply',
       'approaching', 'appropriateness', 'articulate', 'broad', 'broadly',
       'capital', 'challenges', 'circumstances', 'clear', 'clearly',
       'collaborative', 'collaboratively', 'communicate', 'communication',
       'community', 'competencies', 'complex', 'component', 'comprehend',
       'conduct', 'constraints', 'contemporary', 'context',
       'contributions', 'create', 'creatively', 'critical', 'critically',
       'cultural', 'current', 'data', 'defined', 'demands', 'demonstrate',
       'design', 'desired', 'development', 'disciplinary', 'discipline',
       'discuss', 'diverse', 'diversity', 'documentation', 'economic',
       'education', 'effective', 'effectively', 'enabling', 'engage',
       'engagement', 'engineering', 'english', 'enterprise',
       'environmental', 'environments', 'equity', 'ethical', 'everyday',
       'experiments', 'expertise', 'face', 'filipino', 'formulate',
       'function', 'global', 'health', 'human', 'ideas', 'identify',
       'impact', 'independent', 'independently', 'individual',
       'innovative', 'instructions', 'intangible', 'integration',
       'interpret', 'investigations', 'issues', 'justice', 'justify',
       'knowledge', 'language', 'latest', 'leader', 'learning', 'levels',
       'life', 'listen', 'local', 'long', 'make', 'manage', 'management',
       'manufacturability', 'mathematics', 'meet', 'member', 'methods',
       'modern', 'multi', 'multicultural', 'multidisciplinary',
       'national', 'necessary', 'need', 'needs', 'new', 'opportunities',
       'participation', 'perspectives', 'persuasively', 'political',
       'possibilities', 'possible', 'practice', 'presentations',
       'principles', 'problems', 'process', 'professional', 'projects',
       'promote', 'quality', 'quantitative', 'realistic', 'reasoning',
       'receive', 'recognize', 'relevant', 'reports', 'research',
       'respectfully', 'responsibility', 'responsibly', 'safety',
       'science', 'shared', 'social', 'solution', 'solutions', 'solve',
       'specialized', 'standards', 'study', 'sustainability',
       'sustainable', 'sustainably', 'systems', 'tangible', 'team',
       'teams', 'technologies', 'technology', 'theory', 'things', 'think',
       'thinking', 'thoughts', 'tools', 'trans', 'uncertainties',
       'understand', 'understanding', 'using', 'values', 'valuing',
       'views', 'ways', 'work', 'write'], dtype=object)

In [371]:
len(po_feature_names)

182

In [372]:
X1 = pd.DataFrame(po_corpii.toarray(), columns=po_feature_names)
X1

,able,accordance,address,adverse,aligned,analytical,analyze,application,applied,apply,...,uncertainties,understand,understanding,using,values,valuing,views,ways,work,write
0,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,1,1,1,0,0,...,0,0,0,0,0,1,0,0,1,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,0,0,0,1,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,1,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
10,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,1,0,1,0,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

Course Outcome

In [373]:
co_data = co_df.copy()
co_data['CO_Description'] = co_data['CO_Description'].str.lower()
co_corpus = co_data['CO_Description'].tolist()
co_corpii = count_vectorizer.fit_transform(co_corpus)
co_corpii

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 44 stored elements and shape (4, 33)>

In [374]:
co_feature_names = count_vectorizer.get_feature_names_out()
co_feature_names

array(['able', 'business', 'creation', 'creative', 'develop', 'dynamics',
       'enterprise', 'entrepreneurial', 'experience', 'explore',
       'feasibility', 'generation', 'ideas', 'implement', 'investors',
       'key', 'market', 'model', 'needs', 'participating', 'pitch',
       'potential', 'problem', 'process', 'products', 'provide', 'real',
       'services', 'solution', 'students', 'team', 'understand',
       'venture'], dtype=object)

In [375]:
len(co_feature_names)

33

In [376]:
X2 = pd.DataFrame(co_corpii.toarray(), columns=co_feature_names)
X2

,able,business,creation,creative,develop,dynamics,enterprise,entrepreneurial,experience,explore,...,process,products,provide,real,services,solution,students,team,understand,venture
0,1,0,0,1,0,0,0,1,1,0,...,1,0,0,0,0,0,1,0,1,0
1,1,1,1,0,0,0,1,0,0,1,...,0,0,1,0,0,1,1,0,1,0
2,1,0,0,1,0,0,0,0,0,0,...,0,1,0,1,1,0,1,0,0,0
3,1,2,0,0,1,1,0,0,1,0,...,0,0,0,0,0,0,1,1,0,1

In [377]:
U2 = pd.concat([co_data['CO'], X2], axis=1)
U2.set_index('CO', inplace=True)

In [378]:
U1 = pd.concat([po_data['PO'], X1], axis=1)
U1.set_index('PO', inplace=True)

## Intersection method for both CLOs and PLOs

### Generalised list of words

In [379]:
append_words = list(map(str.lower,["list", "recite", "outline", "define", "name", "match", "quote", "recall", "identify", "label", "recognize",
    "describe", "explain", "paraphrase", "restate", "give original examples of", "summarize", "contrast", "interpret", "discuss",
    "calculate", "predict", "apply", "solve", "illustrate", "use", "demonstrate", "determine", "model", "perform", "present",
    "classify", "break down", "categorize", "analyze", "diagram", "illustrate", "criticize", "simplify", "associate",
    "choose", "support", "relate", "determine", "defend", "judge", "grade", "compare", "contrast", "argue", "justify", "support", "convince", "select", "evaluate",
    "design", "formulate", "build", "invent", "create", "compose", "generate", "derive", "modify", "develop"]))

In [380]:
train_column = list(po_feature_names) + append_words
test_column = co_feature_names

In [381]:
train_column = list(co_feature_names) + append_words
test_column = po_feature_names

In [382]:
common_column = list(set(train_column).intersection(set(test_column)))
common_column

['able',
 'create',
 'enterprise',
 'interpret',
 'demonstrate',
 'identify',
 'solve',
 'understand',
 'ideas',
 'needs',
 'discuss',
 'apply',
 'recognize',
 'justify',
 'process',
 'solution',
 'formulate',
 'team',
 'analyze',
 'design']

In [383]:
print(common_column)

['able', 'create', 'enterprise', 'interpret', 'demonstrate', 'identify', 'solve', 'understand', 'ideas', 'needs', 'discuss', 'apply', 'recognize', 'justify', 'process', 'solution', 'formulate', 'team', 'analyze', 'design']

In [384]:
U3 = U2.filter(list(common_column), axis=1)
U3

     able  enterprise  understand  ideas  needs  process  solution  team
CO
CO1     1           0           1      1      0        1         0     0
CO2     1           1           1      0      1        0         1     0
CO3     1           0           0      1      0        0         0     0
CO4     1           0           0      0      0        0         0     1

In [385]:
Cs = []
for x in range(len(po_data)):
    Cs.append(U1.loc[['PO'+str(x+1)]])

In [386]:
Dds = []
for x in range(len(po_data)):
    Dds.append(pd.concat([Cs[x],U3], sort=True))

In [387]:
Ds = []
for x in range(len(po_data)):
    Ds.append(Dds[x].fillna(0))

## Calculate Cosine similarity

In [388]:
for x in range(len(po_data)):
    Dds[x] = pd.DataFrame(cosine_similarity(Ds[x], dense_output=True))

In [389]:
for x in range(len(po_data)):
    Dds[x].rename(columns = {0 :'PO'+str(x+1)}, inplace = True)

In [390]:
Ddn = []
for x in range(len(po_data)):
    Ddn.append(Dds[x]['PO'+str(x+1)])

d = pd.concat(Ddn, axis=1)
dd = d[1:]

In [391]:
dd.reset_index(inplace = True)
dd.drop(['index'], axis=1, inplace = True)

C:\Users\Jestoni Andales\AppData\Local\Temp\ipykernel_5024\2223456261.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dd.drop(['index'], axis=1, inplace = True)

In [392]:
dd

,PO1,PO2,PO3,PO4,PO5,PO6,PO7,PO8,PO9,PO10,PO11,PO12,PO13
0,0.092848,0.000000,0.092848,0.0,0.117851,0.106600,0.111803,0.121268,0.0,0.188982,0.000000,0.117851,0.111803
1,0.083045,0.000000,0.083045,0.0,0.000000,0.095346,0.100000,0.108465,0.0,0.084515,0.000000,0.000000,0.100000
2,0.131306,0.000000,0.000000,0.0,0.166667,0.150756,0.000000,0.000000,0.0,0.267261,0.000000,0.166667,0.158114
3,0.000000,0.129099,0.131306,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.133631,0.182574,0.000000,0.158114

## Setting threshold value (taking min and max of each column and divided by 2)
## threshold value = (min +max)/2

In [393]:
for x in range(len(po_data)):
    tes = dd['PO'+str(x+1)].values.min()
    tes1 = dd['PO'+str(x+1)].values.max()
    tt1 = (tes+tes1)/2
    if tt1 == 0:
      dd['PO'+str(x+1)] = dd['PO'+str(x+1)] 
    else:
      dd['PO'+str(x+1)] = dd['PO'+str(x+1)].apply(lambda x: 1 if x >= tt1 else 0)

C:\Users\Jestoni Andales\AppData\Local\Temp\ipykernel_5024\3140507000.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dd['PO'+str(x+1)] = dd['PO'+str(x+1)].apply(lambda x: 1 if x >= tt1 else 0)
C:\Users\Jestoni Andales\AppData\Local\Temp\ipykernel_5024\3140507000.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dd['PO'+str(x+1)] = dd['PO'+str(x+1)]

In [394]:
dd

   PO1  PO2  PO3  PO4  PO5  PO6  PO7  PO8  PO9  PO10  PO11  PO12  PO13
0    1    0    1  0.0    1    1    1    1  0.0     1     0     1     0
1    1    0    1  0.0    0    1    1    1  0.0     0     0     0     0
2    1    0    0  0.0    1    1    0    0  0.0     1     0     1     1
3    0    1    1  0.0    0    0    0    0  0.0     0     1     0     1

In [395]:
d

,PO1,PO2,PO3,PO4,PO5,PO6,PO7,PO8,PO9,PO10,PO11,PO12,PO13
0,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000
1,0.092848,0.000000,0.092848,0.0,0.117851,0.106600,0.111803,0.121268,0.0,0.188982,0.000000,0.117851,0.111803
2,0.083045,0.000000,0.083045,0.0,0.000000,0.095346,0.100000,0.108465,0.0,0.084515,0.000000,0.000000,0.100000
3,0.131306,0.000000,0.000000,0.0,0.166667,0.150756,0.000000,0.000000,0.0,0.267261,0.000000,0.166667,0.158114
4,0.000000,0.129099,0.131306,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.133631,0.182574,0.000000,0.158114

In [396]:
d= pd.read_csv(HUMAN_MAPPING)
df3 = d.copy()

In [397]:
df3

,CO,CO_Description,PO1,PO2,PO3,PO4,PO5,PO6,PO7,PO8,PO9,PO10,PO11,PO12,PO13
0,CO1,The students will be able to understand and ex...,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN
1,CO2,The students will be able to: 1) understand th...,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN
2,CO3,The students will be able to implement their c...,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN
3,CO4,The students will be able to experience the dy...,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN

In [398]:
for x in range(len(po_data)):
  df3['PO'+str(x+1)] = np.where(dd['PO'+str(x+1)] == df3['PO'+str(x+1)], 'True', 'False')

In [399]:
df3

,CO,CO_Description,PO1,PO2,PO3,PO4,PO5,PO6,PO7,PO8,PO9,PO10,PO11,PO12,PO13
0,CO1,The students will be able to understand and ex...,True,False,True,False,True,True,True,True,False,True,False,False,False
1,CO2,The students will be able to: 1) understand th...,True,False,True,False,False,True,True,True,False,False,False,False,False
2,CO3,The students will be able to implement their c...,True,False,False,False,True,True,False,False,False,True,False,False,False
3,CO4,The students will be able to experience the dy...,False,True,True,False,False,False,False,False,False,False,True,False,False

In [400]:
for x in range(len(po_data)):
  df3['PO'+str(x+1)] = df3['PO'+str(x+1)].replace('True', 1)
  df3['PO'+str(x+1)] = df3['PO'+str(x+1)].replace('False', 0)

C:\Users\Jestoni Andales\AppData\Local\Temp\ipykernel_5024\999122982.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df3['PO'+str(x+1)] = df3['PO'+str(x+1)].replace('False', 0)

In [401]:
df3['Average'] = df3.mean(axis=1, numeric_only=True)
df3

,CO,CO_Description,PO1,PO2,PO3,PO4,PO5,PO6,PO7,PO8,PO9,PO10,PO11,PO12,PO13,Average
0,CO1,The students will be able to understand and ex...,1,0,1,0,1,1,1,1,0,1,0,0,0,0.538462
1,CO2,The students will be able to: 1) understand th...,1,0,1,0,0,1,1,1,0,0,0,0,0,0.384615
2,CO3,The students will be able to implement their c...,1,0,0,0,1,1,0,0,0,1,0,0,0,0.307692
3,CO4,The students will be able to experience the dy...,0,1,1,0,0,0,0,0,0,0,1,0,0,0.230769

In [402]:
df4 = pd.concat([co_data, df3], axis=1)
df4.head()

,CO,CO_Description,CO,CO_Description,PO1,PO2,PO3,PO4,PO5,PO6,PO7,PO8,PO9,PO10,PO11,PO12,PO13,Average
0,CO1,the students will be able to understand and ex...,CO1,The students will be able to understand and ex...,1,0,1,0,1,1,1,1,0,1,0,0,0,0.538462
1,CO2,the students will be able to: 1) understand th...,CO2,The students will be able to: 1) understand th...,1,0,1,0,0,1,1,1,0,0,0,0,0,0.384615
2,CO3,the students will be able to implement their c...,CO3,The students will be able to implement their c...,1,0,0,0,1,1,0,0,0,1,0,0,0,0.307692
3,CO4,the students will be able to experience the dy...,CO4,The students will be able to experience the dy...,0,1,1,0,0,0,0,0,0,0,1,0,0,0.230769

In [403]:
df4.set_index('CO', inplace=True)
df4.head()

,CO_Description,CO_Description,PO1,PO2,PO3,PO4,PO5,PO6,PO7,PO8,PO9,PO10,PO11,PO12,PO13,Average
CO,,,,,,,,,,,,,,,,
"(CO1, CO1)",the students will be able to understand and ex...,The students will be able to understand and ex...,1,0,1,0,1,1,1,1,0,1,0,0,0,0.538462
"(CO2, CO2)",the students will be able to: 1) understand th...,The students will be able to: 1) understand th...,1,0,1,0,0,1,1,1,0,0,0,0,0,0.384615
"(CO3, CO3)",the students will be able to implement their c...,The students will be able to implement their c...,1,0,0,0,1,1,0,0,0,1,0,0,0,0.307692
"(CO4, CO4)",the students will be able to experience the dy...,The students will be able to experience the dy...,0,1,1,0,0,0,0,0,0,0,1,0,0,0.230769

In [404]:
df4['Average'].mean()

np.float64(0.3653846153846154)